### ISSUE TITLE
Change colour theme

### ISSUE THREAD

**Issue by TommyOh0428** [sfuosdev/Docs#7]
The current theme in the documentation tool is green, which is the color of Docusaurus
- Need to change the colour theme for our club

### Requirement

- Find the colour tone that is appropriate/suitable to our club
- Since the Docusaurus supports dark and light themes, need to find two different colour theme
- check /src/css/custom.css for the changing the colour theme

**Comment by AndyZzzZzzZzz** [comment]
Modified the color theme in recent pull request (#10 )
